[project]
name = "tickerlake"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Major Hayden", email = "major@mhtx.net" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas-market-calendars>=5.1.1",
    "polars>=1.33.1",
    "polygon-api-client>=1.15.3",
    "pyarrow>=21.0.0",
    "pydantic-settings>=2.10.1",
    "rich>=14.1.0",
    "s3fs>=2025.9.0",
    "structlog>=25.4.0",
]

[project.scripts]
tickerlake = "tickerlake:main"

[build-system]
requires = ["uv_build>=0.8.16,<0.9.0"]
build-backend = "uv_build"
