CREATE SCHEMA IF NOT EXISTS market;
CREATE SCHEMA IF NOT EXISTS ingest;
CREATE TABLE IF NOT EXISTS ingest.schema_migration (
    version integer PRIMARY KEY,
    filename text NOT NULL UNIQUE,
    checksum text NOT NULL CHECK (checksum ~ '^[0-9a-f]{64}$'),
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE market.ticker (
    ticker_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol text NOT NULL UNIQUE CHECK (btrim(symbol) <> ''),
    name text,
    -- Canonical allowlist lives in tickerlake.config._ALLOWED_TICKER_TYPES.
    ticker_type text CHECK (ticker_type IS NULL OR ticker_type = ANY (ARRAY['CS','ETF','ETV','ETN','ADRC'])),
    primary_exchange text,
    cik text CHECK (cik IS NULL OR (length(cik) BETWEEN 1 AND 10 AND cik ~ '^[A-Za-z0-9-]+$')),
    active boolean
);

CREATE TABLE ingest.raw_daily (
    date date NOT NULL,
    ticker_id integer NOT NULL REFERENCES market.ticker(ticker_id),
    open real NOT NULL,
    high real NOT NULL,
    low real NOT NULL,
    close real NOT NULL,
    volume double precision NOT NULL,
    PRIMARY KEY (date, ticker_id),
    CHECK (volume >= 0),
    CHECK (high >= GREATEST(open, close, low) AND low <= LEAST(open, close, high))
);

CREATE TABLE ingest.ticker_reference (
    ticker_id integer PRIMARY KEY REFERENCES market.ticker(ticker_id),
    name text,
    ticker_type text,
    primary_exchange text,
    cik text,
    active boolean
);

CREATE TABLE ingest.split_event (
    split_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id integer NOT NULL REFERENCES market.ticker(ticker_id),
    execution_date date NOT NULL,
    split_from real NOT NULL,
    split_to real NOT NULL,
    adjustment_factor double precision NOT NULL,
    -- Massive's splits endpoint returns 'forward' for cumulative adjustment
    -- events; NULL is allowed when the field is absent.
    adjustment_type text CHECK (adjustment_type IS NULL OR adjustment_type = 'forward'),
    CHECK (split_from NOT IN ('NaN'::real, 'Infinity'::real, '-Infinity'::real) AND split_from > 0),
    CHECK (split_to NOT IN ('NaN'::real, 'Infinity'::real, '-Infinity'::real) AND split_to > 0),
    CHECK (adjustment_factor NOT IN ('NaN'::double precision, 'Infinity'::double precision, '-Infinity'::double precision) AND adjustment_factor > 0),
    CONSTRAINT split_event_natural_key UNIQUE NULLS NOT DISTINCT
        (ticker_id, execution_date, split_from, split_to, adjustment_factor, adjustment_type)
);

CREATE TABLE ingest.cache_state (
    cache_state_id integer PRIMARY KEY DEFAULT 1 CHECK (cache_state_id = 1),
    input_revision bigint NOT NULL DEFAULT 0 CHECK (input_revision >= 0),
    retained_start date,
    retained_end date,
    CHECK ((retained_start IS NULL) = (retained_end IS NULL)),
    CHECK (retained_start IS NULL OR retained_start <= retained_end)
);
INSERT INTO ingest.cache_state (cache_state_id, input_revision, retained_start, retained_end)
VALUES (1, 0, NULL, NULL);

CREATE TABLE ingest.run (
    run_id uuid PRIMARY KEY,
    target_date date NOT NULL,
    requested_start date,
    requested_end date,
    input_revision bigint NOT NULL CHECK (input_revision >= 0),
    version text NOT NULL CHECK (length(version) BETWEEN 1 AND 64),
    state text NOT NULL CHECK (state IN ('running', 'completed', 'failed', 'published')),
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    published_at timestamptz,
    failure_code text CHECK (failure_code IS NULL OR failure_code = ANY (ARRAY['storage_error','connection_lost','incomplete_fetch','validation_error','operator_cancelled'])),
    CHECK ((requested_start IS NULL) = (requested_end IS NULL)),
    CHECK (requested_start IS NULL OR requested_start <= requested_end),
    CHECK ((state = 'running' AND ended_at IS NULL AND published_at IS NULL)
        OR (state = 'completed' AND ended_at IS NOT NULL AND published_at IS NULL)
        OR (state = 'failed' AND ended_at IS NOT NULL AND published_at IS NULL)
        OR (state = 'published' AND ended_at IS NOT NULL AND published_at IS NOT NULL))
);

CREATE TABLE ingest.fetch_manifest (
    manifest_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES ingest.run(run_id),
    source text NOT NULL CHECK (source IN ('daily', 'tickers', 'splits')),
    requested_date date,
    requested_start date,
    requested_end date,
    requested_ticker_types text[],
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    status text NOT NULL CHECK (status IN ('failed', 'quarantined', 'populated', 'successful_empty')),
    row_count bigint NOT NULL DEFAULT 0 CHECK (row_count >= 0),
    diagnostic_code text CHECK (diagnostic_code IS NULL OR diagnostic_code ~ '^[a-z][a-z0-9_]{0,63}$'),
    CHECK ((requested_start IS NULL) = (requested_end IS NULL)),
    CHECK (requested_start IS NULL OR requested_start <= requested_end),
    CHECK (requested_ticker_types IS NULL OR cardinality(requested_ticker_types) > 0),
    CHECK (finished_at IS NULL OR finished_at >= started_at)
);

REVOKE ALL ON SCHEMA ingest FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON SCHEMA market FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON ALL TABLES IN SCHEMA ingest FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON ALL TABLES IN SCHEMA market FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA ingest FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA market FROM PUBLIC, tickerlake_etl, tickerlake_reader;
REVOKE ALL ON ingest.schema_migration FROM PUBLIC, tickerlake_etl, tickerlake_reader;

GRANT USAGE ON SCHEMA ingest TO tickerlake_etl;
GRANT SELECT, INSERT, UPDATE, DELETE ON
    ingest.cache_state,
    ingest.run,
    ingest.fetch_manifest,
    ingest.raw_daily,
    ingest.ticker_reference,
    ingest.split_event
TO tickerlake_etl;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ingest TO tickerlake_etl;
GRANT USAGE ON SCHEMA market TO tickerlake_etl, tickerlake_reader;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA market TO tickerlake_etl;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA market TO tickerlake_etl;
GRANT SELECT ON ALL TABLES IN SCHEMA market TO tickerlake_reader;

DO $grant_temp$
BEGIN
    EXECUTE format('GRANT TEMPORARY ON DATABASE %I TO tickerlake_etl', current_database());
END;
$grant_temp$;
