{{- if and .Values.massive.apiKey (not .Values.massive.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-massive" (include "tickerlake.fullname" .) }}
  labels:
    {{- include "tickerlake.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.massive.secretKey }}: {{ .Values.massive.apiKey | b64enc | quote }}
{{- end }}
