name: Tests

on:
  push:
    branches:
      - main
      - unified
  pull_request:
    branches:
      - main
      - unified
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7
        with:
          version: "latest"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run all checks
        run: make all
